name: DAST with Zap OWASP

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            ref: master
        - name: ZAP Scan
          uses: zaproxy/action-full-scan@v0.12.0
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
            target: 'https://www.zaproxy.org/'
            rules_file_name: '.zap/rules.tsv'
            cmd_options: '-a'