name: Linting with pylint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
#      - name: Installer les dépendances Python
 #       run:  |
  #        python -m pip install --upgrade pip
   #       pip install -r requirements.txt
      - name: pylint check
        uses: Silleellie/pylint-github-action@v2.1
        with:
          lint-path: sqli
          python-version: 3.9
      - name: Semgrep Scan
        uses: MetaMask/Semgrep-action@main
      - name: Build and start services
        run: docker compose up --build -d
      - name: Wait for the launch
        run: sleep 10
      - name: Security Scan of the app with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'dvmpa-app'
          format: 'table'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
      - name: Security Scan of the DB with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'dvmpa-postgres'
          format: 'table'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
      - name: Stop and clean containers
        if: always()
        run: docker compose down